#!/bin/sh
# Start/stop the alarmserver daemon.
#
### BEGIN INIT INFO
# Provides:          alarmserver
# Required-Start:    $remote_fs $syslog $time
# Required-Stop:     $remote_fs $syslog $time
# Should-Start:      $network $named slapd autofs ypbind nscd nslcd winbind
# Should-Stop:       $network $named slapd autofs ypbind nscd nslcd winbind
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Regular background program processing daemon
# Description:       alarmserver is a standard UNIX program that runs user-specified 
#                    programs at periodic scheduled times. vixie cron adds a 
#                    number of features to the basic UNIX cron, including better
#                    security and more powerful configuration options.
### END INIT INFO

# Source function library.
. /lib/lsb/init-functions

PATH=/bin:/usr/bin:/sbin:/usr/sbin
DAEMON=/usr/local/bin/alarmserver
PIDFILE=/var/run/alarmserver.pid
DESC="alarmserver daemon"
NAME=alarmserver
SCRIPTNAME=/etc/init.d/"$NAME"

test -f $DAEMON || exit 0




case "$1" in
start)	log_daemon_msg "Starting alarmserver daemon"
        start_daemon -p $PIDFILE $DAEMON
        log_end_msg $?
	;;
stop)	log_daemon_msg "Stopping alarmserver daemon"
        kill -9 $(cat $PIDFILE)
        killproc -p $PIDFILE $DAEMON
        RETVAL=$?
        [ $RETVAL -eq 0 ] && [ -e "$PIDFILE" ] && rm -f $PIDFILE
        log_end_msg $RETVAL
        ;;
restart) log_daemon_msg "Restarting alarmserver daemon" 
        $0 stop
        $0 start
        ;;
status)
        status_of_proc -p $PIDFILE $DAEMON $NAME && exit 0 || exit $?
        ;;
*)	log_action_msg "Usage: /etc/init.d/alarmserverd {start|stop|status|restart|reload|force-reload}"
        exit 2
        ;;
esac
exit 0